<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-BL03I3N" name="com.training.sanity.tests.LoginTests" tests="1" failures="0" timestamp="17 Jul 2019 05:54:16 GMT" time="1.053" errors="1">
  <testcase name="timeOutTest" time="1.053" classname="com.training.sanity.tests.LoginTests">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.training.sanity.tests.LoginTests.timeOutTest() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.training.sanity.tests.LoginTests.timeOutTest() didn't finish within the time-out 1000
]]>
    </error>
  </testcase> <!-- timeOutTest -->
</testsuite> <!-- com.training.sanity.tests.LoginTests -->
